;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Fleet]
Pos=715,1
Size=1191,865
Collapsed=1

[Window][Controls]
Pos=5,5
Size=347,258
Collapsed=0

[Window][Event Log]
Pos=4,734
Size=1911,463
Collapsed=0
DockId=0x00000001,0

[Window][Locations]
Pos=332,40
Size=1583,690
Collapsed=0

[Window][Commodity History]
Pos=4,734
Size=1911,463
Collapsed=0
DockId=0x00000001,2

[Window][Faction Net Worth]
Pos=4,734
Size=1911,463
Collapsed=0
DockId=0x00000001,1

[Window][Stockpile History]
Pos=4,734
Size=1911,463
Collapsed=0
DockId=0x00000001,3

[Table][0x350CFD74,4]
Column 0  Weight=0.5477
Column 1  Weight=0.2411
Column 2  Weight=1.3154
Column 3  Weight=1.8958

[Table][0x16FAF715,7]
Column 0  Weight=1.2766
Column 1  Weight=1.2363
Column 2  Weight=1.1624
Column 3  Weight=0.7189
Column 4  Weight=0.7727
Column 5  Weight=0.8331
Column 6  Weight=1.0000

[Table][0x84E09416,4]
RefScale=23
Column 0  Width=50
Column 1  Width=110
Column 2  Width=227
Column 3  Weight=1.0000

[Docking][Data]
DockNode  ID=0x00000001 Pos=4,734 Size=1911,463 Selected=0xD071B094

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
